# Generated by Django 4.1 on 2022-09-05 07:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Total',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vehicle_id', models.CharField(max_length=64, verbose_name='VehicleID')),
                ('company', models.CharField(max_length=64, verbose_name='Company')),
                ('currentdate', models.CharField(default='09-05-2022', max_length=64, verbose_name='CurrentDate')),
                ('currenttime', models.CharField(default='14-51-23', max_length=64, verbose_name='CurrentTime')),
                ('road', models.CharField(default='NanyangLink', max_length=64, verbose_name='Road')),
                ('suburb', models.CharField(default='JurongWest', max_length=64, verbose_name='Suburb')),
                ('county', models.CharField(default='Pioneer', max_length=64, verbose_name='County')),
                ('postcode', models.IntegerField(default=0, verbose_name='Postcode')),
                ('avg_unclean_level', models.IntegerField(default=0, verbose_name='AvgUncleanLevel')),
                ('duration', models.IntegerField(default=0, verbose_name='Duration')),
                ('latitude', models.FloatField(default=1.3422035, verbose_name='Latitude')),
                ('longitude', models.FloatField(default=103.681429, verbose_name='Longitude')),
            ],
        ),
    ]
